# Site settings
title: See Lab @ HWU Malaysia
name: See Lab @ HWU Malaysia
email: j.see@hw.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Computer Vision, Machine Learning, Affective Computing. Research group headed by John See, PhD at
  the School of Mathematical and Computing Sciences, Heriot-Watt University Malaysia.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://see-lab.github.io"
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
twitter_username: johnseesuyang
github_username:  jstulips
linkedin_username: john-see
scholar_userid: uH74dcgAAAAJ
orcid_id: 0000-0003-3005-4109
dblp_url: "36/4809"
work_url: "https://www.johnsee.net"

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
navbar_fixed: true

# -----------------------------------------------------------------------------
# News
# -----------------------------------------------------------------------------
blog_name: See Lab @ HWU Malaysia
blog_description: computer vision | machine learning | affective computing

# Pagination
paginate: 4
permalink: /news/:year/:title/
paginate_path: "news/page:num"

text:
  pagination:
    newer: 'Newer'
    older: 'Older'


# Optional features
show_social_icons: true
enable_anchorjs:    false
enable_katex:       true
enable_darkmode:  true


# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /updates/:path/
  projects:
    output: true
    permalink: /projects/:path/
  pastsem:
    output: true
    permalink: /pastsem/:path/

news_limit: 25


# Build settings
markdown: kramdown
highlighter: rouge
highlight_theme: github

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji
    - jekyll-sitemap
    - jekyll/scholar
    - jekyll-github-metadata

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"

bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
