# Site settings
title: See Lab @ HWU
name: See Lab at HWU
email: j.see@hw.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Computer Vision, Affective Computing. Research group headed by John See, PhD at
  the School of Mathematical and Computing Sciences, Heriot-Watt University Malaysia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://see-lab.github.io"
last_updated: # leave blank if you don't want to display last updated
twitter_username: johnseesuyang
github_username:  jstulips


# -----------------------------------------------------------------------------
# News
# -----------------------------------------------------------------------------
blog_name: See Lab @ HWU Malaysia
blog_description: computer vision | pattern recognition | affective computing

# Pagination
paginate: 4
permalink: /news/:year/:title/
paginate_path: "news/page:num"

text:
  pagination:
    newer: 'Newer'
    older: 'Older'


# Optional features
show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true


# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /updates/:path/
  projects:
    output: true
    permalink: /projects/:path/
  pastsem:
    output: true
    permalink: /pastsem/:path/

news_limit: 5


# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji
    - jekyll-sitemap


# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
